### ISSUE TITLE
[1.1.x & Xcode9] start extension restarts simulator if already running

### ISSUE THREAD

**Issue by marcocarosi** [ios-control/simctl#16]
# Expected behavior

This library is used by ios-sim.
To test you can could use `ios-sim launch` with the proper parameters.
If the simulator is already running, it should just start install/launch the desired app.

Note that that was the normal behavior, that got broken from versions after the 1.0.1

# Actual behavior.

The simulator exits, and then starts again, before installing/launching the desired app.
Refer to https://github.com/phonegap/ios-sim/issues/223
However the issue is on this library.

# Steps to reproduce the problem

```
ios-sim start --devicetype "..."
# Wait for it to start
ios-sim launch --devicetype "..." "..."
# Observe that the simulator exits & then restarts
```

# Proposed solutions
The following code replacing the start extension in file `simctl-extensions.js fixes this issue:

```
    start: function(deviceid) {
        var is_at_least_xcode_9 = false;

        // var command = 'killall Simulator';
        // shell.exec(command, { silent: true });

        command = 'xcodebuild -version';
        var output = shell.exec(command, { silent: true }).output;

        // parse output for Xcode version
        var versionMatch = /Xcode (.*)/.exec(output);
        if (!versionMatch) {
            console.log('Unable to parse xcodebuild version.');
            return;
        } else {
            is_at_least_xcode_9 = (parseInt(versionMatch[1]) >= 9);
        }

        if (is_at_least_xcode_9) {
            // Xcode 9 or greater
            command = util.format('xcrun simctl list -j');
            var res = shell.exec(command, { silent: true });
            if (res.code !== 0) {
                console.log('Unable to parse xcodebuild version.');
                return;
            }
            let output = JSON.parse(res.output);
            // Object.keys(output.devices).reduce( (acc, key) => acc.concat(output.devices[key]), []).find(el => el.udid === deviceid);
            var device = Object.keys(output.devices)
                .reduce( function(acc, key) { return acc.concat(output.devices[key]) }, [])
                .find( function (el) { return el.udid === deviceid });
            // console.log('Simulator device info: ', device);          
            if (device.state === 'Booted') {
                // no need to launch the emulator, it is already running
                console.log('Simulator already running.');
                return;
            }
            command = util.format('xcrun simctl boot "%s"', deviceid);
            shell.exec(command, { silent: true });
            command = 'open `xcode-select -p`/Applications/Simulator.app';
            return shell.exec(command, { silent: true });
        } else {
            // Xcode 8 or older
            // command = util.format('xcrun simctl shutdown booted');
            // shell.exec(command, { silent: true });
            command = util.format('xcrun instruments -w "%s"', deviceid);
            return shell.exec(command, { silent: true });
        }
    }
```

**Comment by marcocarosi** [comment]
@shazron 
the above code works for our team working on cordova / ionic projects.
If you believe the above code is a valid fix, I will be glad to submit a PR after cleaning up the unnecessary comments.

**Comment by jbotte** [comment]
has this been implemented? where would i be editing this file, is it in my global node modules?

**Comment by shazron** [comment]
@marcocarosi thank you! Looks sound, please submit that PR.

**Comment by jonworek** [comment]
This would be great to see a fix make it into a release.  

The problem that this issue causes for me is that when I'm debugging the webview using Safari's inspector, I have to restart Safari after the simulator is restarted to pick up debugging on the new version of the app.  If the simulator is left open, I'm able to continue using Safari's inspector.

_first run_
![screen shot 2018-08-12 at 12 02 55 pm](https://user-images.githubusercontent.com/3124548/44003847-b287d68a-9e27-11e8-99b4-541281aa1db1.png)

_after simulator restarts, Safari won't reconnect_
![screen shot 2018-08-12 at 12 05 15 pm](https://user-images.githubusercontent.com/3124548/44003863-0222ec98-9e28-11e8-9e17-347ceefa5b81.png)

**Comment by fareshan** [comment]
+1

**Comment by shazron** [comment]
Put the proposed code into PR #17
