### ISSUE TITLE
Update shelljs to 0.8.5 to resolve npm audit security vulnerability

### ISSUE THREAD

**Issue by almercier** [ios-control/simctl#27]
This module depends on a version of shelljs that is listed as containing a security vulnerability per npm audit. https://github.com/advisories/GHSA-64g7-mvw6-v9qj

This has since been resolved in the newest version of shellJS
https://github.com/shelljs/shelljs/releases/tag/v0.8.5

**Comment by shazron** [comment]
fixed in https://github.com/ios-control/simctl/commit/9f2ef9aaa5b9f602c3f013c6791071023e9b3627
