### ISSUE TITLE
unable to get device details, possibly due to recent update in shelljs version

### ISSUE THREAD

**Issue by CodeWithOz** [ios-control/simctl#30]
It appears the recent update of the `shelljs` version (in #27) has introduced a regression. [This line](https://github.com/ios-control/simctl/blob/14c2efea7dfc173fc3b0b029ba66592f850758a9/simctl.js#L171) now throws an error:
```
Error: Unhandled error. ('[ios-sim] SyntaxError: Unexpected token u in JSON at position 0\n' +
  '    at JSON.parse (<anonymous>)\n' +
  '    at Object.list (/Users/{user}/Documents/{project}/node_modules/simctl/simctl.js:173:33)\n' +
  '    at getDeviceFromDeviceTypeId (/Users/{user}/Documents/{project}/node_modules/ios-sim/src/lib.js:155:21)\n' +
  '    at /Users/{user}/Documents/{project}/node_modules/ios-sim/src/lib.js:460:22\n' +
  '    at withInjectedEnvironmentVariablesToProcess (/Users/{user}/Documents/{project}/node_modules/ios-sim/src/lib.js:269:3)\n' +
  '    at /Users/{user}/Documents/{project}/node_modules/ios-sim/src/lib.js:457:7\n' +
  '    at tryParseBuffer (/Users/{user}/Documents/{project}/node_modules/ios-sim/node_modules/bplist-parser/bplistParser.js:25:5)\n' +
  '    at /Users/{user}/Documents/{project}/node_modules/ios-sim/node_modules/bplist-parser/bplistParser.js:33:7\n' +
  '    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)\n')
```

I noticed that `obj` itself now contains the json string (`obj.output` is now undefined), so I tried changing the code to:
```
            try {
                obj.json = JSON.parse(obj.output);
            } catch (err) {
                // console.error(err.stack);
                obj.json = JSON.parse(obj);
            }
```
That gave a different error:
```
Error: Unhandled error. ('[ios-sim] An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):\n' +
  'Unable to lookup in current state: Shutdown\n')
```

So I think there are other bits of logic that are affected by the shelljs update apart from the line of code I saw.

**Comment by mrister** [comment]
seem to be having the same issue also!
```text
+ npm install ios-sim -g
/Users/vagrant/.nvm/versions/node/v14.18.2/bin/ios-sim -> /Users/vagrant/.nvm/versions/node/v14.18.2/lib/node_modules/ios-sim/bin/ios-sim
+ ios-sim@9.0.0
added 117 packages from 78 contributors in 7.873s
+ xcode-select --print-path
/Applications/Xcode-13.1.Release.Candidate.app/Contents/Developer
+ ios-sim showsdks
+ true
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.list (/Users/vagrant/.nvm/versions/node/v14.18.2/lib/node_modules/ios-sim/node_modules/simctl/simctl.js:171:33)
    at ShowSdksCommand.run (/Users/vagrant/.nvm/versions/node/v14.18.2/lib/node_modules/ios-sim/src/commands/showsdks.js:7:25)
    at ShowSdksCommand._run (/Users/vagrant/.nvm/versions/node/v14.18.2/lib/node_modules/ios-sim/node_modules/@oclif/command/lib/command.js:43:31)
    TypeError: Cannot read property 'runtimes' of undefined
+ ios-sim showdevicetypes
+ true
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.list (/Users/vagrant/.nvm/versions/node/v14.18.2/lib/node_modules/ios-sim/node_modules/simctl/simctl.js:171:33)
    at getDeviceTypes (/Users/vagrant/.nvm/versions/node/v14.18.2/lib/node_modules/ios-sim/src/helpers.js:29:21)
    at ShowDeviceTypesCommand.run (/Users/vagrant/.nvm/versions/node/v14.18.2/lib/node_modules/ios-sim/src/commands/showdevicetypes.js:7:25)
    at ShowDeviceTypesCommand._run (/Users/vagrant/.nvm/versions/node/v14.18.2/lib/node_modules/ios-sim/node_modules/@oclif/command/lib/command.js:43:31)
    TypeError: Cannot read property 'devicetypes' of undefined
+ ios-sim start -d iPhone-12-Pro -x
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.list (/Users/vagrant/.nvm/versions/node/v14.18.2/lib/node_modules/ios-sim/node_modules/simctl/simctl.js:171:33)
    at getDeviceFromDeviceTypeId (/Users/vagrant/.nvm/versions/node/v14.18.2/lib/node_modules/ios-sim/src/helpers.js:196:21)
    at StartCommand.run (/Users/vagrant/.nvm/versions/node/v14.18.2/lib/node_modules/ios-sim/src/commands/start.js:10:20)
    at StartCommand._run (/Users/vagrant/.nvm/versions/node/v14.18.2/lib/node_modules/ios-sim/node_modules/@oclif/command/lib/command.js:43:31)
    TypeError: Cannot read property 'devicetypes' of undefined
```

**Comment by CodeWithOz** [comment]
@mrister have you found a workaround for now?

**Comment by mrister** [comment]
@CodeWithOz unfortunately no, I had to resort to using `xcrun simctl list devices` and `xcrun simctl boot` to run the simulator

**Comment by tzmartin** [comment]
`simctl.js`
LN 175: Change `obj.output` to `obj.stdout`

**Comment by ezilox** [comment]
Also experience the same issue :(

**Comment by radykal** [comment]
I got the same issue using Cordova in Meteor. I created two meteor projects with cordova. In the first one it is working, but in the other project with the same env I got the same error as mentioned above. Now I debugged the code and it seems there is a problem with the sync shell execution.

I pasted an sync call after line 166 in the code and detect that the correct output is stored in the stdout of the callback function.


         var command = util.format('xcrun simctl list %s --json', sublist);

         var obj = shell.exec(command, { silent: options.silent });

		shell.exec(command, { silent: options.silent }, (code, stdout, stderr) => {
	    	console.log('Exit code:', code);
			console.log('Program output:', stdout);
			console.log('Program stderr:', stderr);
		});

        if (obj.code === 0) {
            try {
                obj.json = obj.output ? JSON.parse(obj.output) : JSON.parse(obj.stdout);
            } catch (err) {
                console.error(err.stack);
            }
        }

**Comment by mrister** [comment]
> I got the same issue using Cordova in Meteor. I created two meteor projects with cordova. In the first one it is working, but in the other project with the same env I got the same error as mentioned above. Now I debugged the code and it seems there is a problem with the async shell execution.
> 
> I pasted an sync call after line 166 in the code and detect that the correct output is stored in the stdout of the callback function.
> 
> ```
>      var command = util.format('xcrun simctl list %s --json', sublist);
> 
>      var obj = shell.exec(command, { silent: options.silent });
> 
> 	shell.exec(command, { silent: options.silent }, (code, stdout, stderr) => {
>     	console.log('Exit code:', code);
> 		console.log('Program output:', stdout);
> 		console.log('Program stderr:', stderr);
> 	});
> 
>     if (obj.code === 0) {
>         try {
>             obj.json = obj.output ? JSON.parse(obj.output) : JSON.parse(obj.stdout);
>         } catch (err) {
>             console.error(err.stack);
>         }
>     }
> ```

@radykal how bout a PR since this breaking change does not seem to get the attention of maintainer(s) here

**Comment by antares-farias** [comment]
what works for me was to directly install in the project the previews version of the simctl

npm install simctl@2.0.0

**Comment by XtoZee** [comment]
> what works for me was to directly install in the project the previews version of the simctl
> 
> npm install simctl@2.0.0

Worked for me as a temporary solution.

Could not run Cordova 10 app in simulator. Got error on "Deploing to simulator" phase. (XCode 12.4, node v14.7.0, cordova-ios 6.2.0)

> Error: Unhandled error. ('[ios-sim] SyntaxError: Unexpected token u in JSON at position 0

**Comment by mrister** [comment]
@shazron @marekkalnik can anybody of you perhaps implement a fix, this is breaking.

**Comment by airdrummingfool** [comment]
@shazron I've opened a PR (#31), please take a look. Thanks @tzmartin for the fix suggestion.
